# SwiftLint Configuration — TherapyRecorder
# Enforces modern Swift 6 patterns, strict concurrency, and HIPAA-safe coding practices.

excluded:
  - .build
  - Pods
  - "**/*.generated.swift"

opt_in_rules:
  # Swift 6 / Modern Swift
  - closure_body_length
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - shorthand_optional_binding
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - yoda_condition

  # Concurrency
  - strict_fileprivate

  # Imports
  - unused_import

  # Closures
  - unused_closure_parameter

disabled_rules:
  # Conflicts with SwiftUI trailing closure patterns
  - multiple_closures_with_trailing_closure

# --- Severity Thresholds ---

line_length:
  warning: 120
  error: 200

file_length:
  warning: 400
  error: 600

function_body_length:
  warning: 40
  error: 80

cyclomatic_complexity:
  warning: 10
  error: 20

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - i
    - x
    - y

# --- Error-Level Rules (Critical for Audio/Security Code) ---

force_unwrapping: error
force_cast: error
force_try: error

trailing_whitespace:
  ignores_empty_lines: true

trailing_newline: warning

# --- Custom Rules ---

custom_rules:
  no_print_statements:
    name: "No print() Statements"
    regex: "\\bprint\\s*\\("
    message: "Use os.log or Logger instead of print() for HIPAA compliance. No PHI must leak to console."
    severity: error
    match_kinds:
      - identifier
    excluded: ".*Tests.*\\.swift"
